
name: Isw2-CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup native build
        uses: ./.github/actions/setup-native-build

      - name: Build
        run: mvn -T 1C -B -nsu clean install -Ddistributedlog -DskipTests
